module.exports = [
  {
    id: 1,
    user_id: 6,
    movie_id: 6,
    caption: "Highly enjoyable movie!",
    rating: 7,
    is_post: 1,
  },
  {
    id: 2,
    user_id: 4,
    movie_id: 24,
    caption:
      "Whiplash is a cinematic whirlwind that immerses its audience in the cutthroat world of music education. Damien Chazelle's direction, paired with stellar performances by Miles Teller and J.K. Simmons, creates an intense and riveting narrative. The film's heartbeat is the drumming, both in its musical sequences and in the relentless pacing that mirrors the pursuit of greatness. Simmons' portrayal of the tyrannical music instructor is chilling and magnetic, while Teller's drumming protagonist embodies the physical and emotional toll of aspiring to perfection. Whiplash is a tour de force, a psychological thriller that hits every beat with precision and leaves a lasting impact. Chazelle's film is not just a tale of music; it's a visceral exploration of ambition, sacrifice, and the blurred lines between mentorship and abuse. The tension in the relationship between student and instructor is palpable, creating an emotional whirlwind that keeps the audience engaged until the final drumroll. Whiplash stands as a testament to the cost of pursuing excellence, offering a gripping and thought-provoking experience that resonates long after the credits roll.",
    rating: 9,
    is_post: 1,
  },
  {
    id: 3,
    user_id: 1,
    movie_id: 3,
    caption: "",
    rating: 2,
    is_post: 0,
  },
  {
    id: 4,
    user_id: 1,
    movie_id: 11,
    caption: "One of my all time favorite movies.",
    rating: 10,
    is_post: 1,
  },
  {
    id: 5,
    user_id: 3,
    movie_id: 25,
    caption:
      "Inception is a mind-bending masterpiece that seamlessly blends high-octane action with intricate, cerebral storytelling. Christopher Nolan's ambitious and visually stunning film challenges the audience to navigate the layers of dreams within dreams, creating a narrative labyrinth that keeps viewers on the edge of their seats. The film's ensemble cast, led by the charismatic Leonardo DiCaprio, delivers powerhouse performances that add emotional depth to the complex plot. Hans Zimmer's iconic score serves as the heartbeat of the movie, intensifying the already gripping scenes. The visual effects are groundbreaking, transforming the dream world into a mesmerizing and unpredictable landscape. What sets Inception apart is its intellectual depth, exploring profound themes such as the nature of reality, the power of dreams, and the fragility of memory. Nolan's audacious storytelling challenges viewers to question their own perceptions and adds a layer of philosophical intrigue to the pulse-pounding action. While some critics argue that the film's complexity may be a barrier for casual viewers, it is precisely this intricacy that makes Inception a cinematic gem. Nolan's commitment to pushing the boundaries of conventional storytelling cements Inception as a modern classic, a film that demands multiple viewings to fully grasp its brilliance. In the realm of mind-bending thrillers, Inception reigns supreme, leaving an indelible mark on the landscape of contemporary cinema.",
    rating: 8,
    is_post: 1,
  },
  {
    id: 6,
    user_id: 14,
    movie_id: 13,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 7,
    user_id: 5,
    movie_id: 14,
    caption:
      "Fight Club, directed by David Fincher, is a nihilistic and testosterone-fueled descent into toxic masculinity that ultimately falls short of its ambitious aspirations. While the film boasts Fincher's signature dark and stylish visuals, the narrative's attempt to dissect societal disillusionment and rebellion results in a convoluted and pretentious mess. The central characters, played by Edward Norton and Brad Pitt, come off as caricatures of discontent, and the film's attempts to subvert traditional storytelling often feel more like a desperate grab for shock value than a meaningful exploration of its themes. As the plot unravels into a chaotic blend of violence and anarchy, the supposed profundity of the film becomes increasingly muddled. The twist, intended to be a mind-bending revelation, feels forced and gimmicky, overshadowing any potential depth in the commentary on consumer culture and societal malaise. Fight Club might have been revolutionary in its approach, but its impact is diminished by a lack of nuance, leaving the viewer with a hollow sense of dissatisfaction and a film that fails to deliver on the intellectual and emotional levels it aspires to reach.",
    rating: 4,
    is_post: 1,
  },
  {
    id: 8,
    user_id: 14,
    movie_id: 14,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 9,
    user_id: 14,
    movie_id: 15,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 10,
    user_id: 14,
    movie_id: 16,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 11,
    user_id: 14,
    movie_id: 17,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 12,
    user_id: 14,
    movie_id: 18,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 13,
    user_id: 14,
    movie_id: 19,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 14,
    user_id: 14,
    movie_id: 20,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 15,
    user_id: 14,
    movie_id: 21,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 16,
    user_id: 14,
    movie_id: 22,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 17,
    user_id: 14,
    movie_id: 23,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 18,
    user_id: 14,
    movie_id: 24,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 19,
    user_id: 14,
    movie_id: 25,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 20,
    user_id: 14,
    movie_id: 26,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 21,
    user_id: 14,
    movie_id: 27,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 22,
    user_id: 14,
    movie_id: 28,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 23,
    user_id: 1,
    movie_id: 1,
    caption:
      "Outstanding display from Cillian Murphy. The rich, dialogue-heavy script was well matched by powerful performances across the cast assemble.",
    rating: 9,
    is_post: 1,
  },
  {
    id: 24,
    user_id: 1,
    movie_id: 26,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 25,
    user_id: 14,
    movie_id: 29,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 26,
    user_id: 2,
    movie_id: 3,
    caption: "",
    rating: 5,
    is_post: 0,
  },
  {
    id: 27,
    user_id: 2,
    movie_id: 4,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 28,
    user_id: 2,
    movie_id: 28,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 29,
    user_id: 2,
    movie_id: 29,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 30,
    user_id: 2,
    movie_id: 27,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 31,
    user_id: 2,
    movie_id: 30,
    caption: "",
    rating: 5,
    is_post: 0,
  },
  {
    id: 32,
    user_id: 2,
    movie_id: 31,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 33,
    user_id: 2,
    movie_id: 25,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 34,
    user_id: 2,
    movie_id: 14,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 35,
    user_id: 2,
    movie_id: 24,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 36,
    user_id: 2,
    movie_id: 11,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 37,
    user_id: 2,
    movie_id: 1,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 38,
    user_id: 2,
    movie_id: 32,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 39,
    user_id: 2,
    movie_id: 33,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 40,
    user_id: 2,
    movie_id: 34,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 41,
    user_id: 2,
    movie_id: 35,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 42,
    user_id: 2,
    movie_id: 36,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 43,
    user_id: 2,
    movie_id: 6,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 44,
    user_id: 2,
    movie_id: 37,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 45,
    user_id: 2,
    movie_id: 38,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 46,
    user_id: 2,
    movie_id: 39,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 47,
    user_id: 2,
    movie_id: 22,
    caption: "",
    rating: 9,
    is_post: 1,
  },
  {
    id: 48,
    user_id: 2,
    movie_id: 40,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 49,
    user_id: 3,
    movie_id: 1,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 50,
    user_id: 3,
    movie_id: 14,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 51,
    user_id: 3,
    movie_id: 24,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 52,
    user_id: 3,
    movie_id: 26,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 53,
    user_id: 3,
    movie_id: 27,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 54,
    user_id: 4,
    movie_id: 1,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 55,
    user_id: 4,
    movie_id: 26,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 56,
    user_id: 4,
    movie_id: 14,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 57,
    user_id: 4,
    movie_id: 41,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 58,
    user_id: 4,
    movie_id: 42,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 59,
    user_id: 4,
    movie_id: 43,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 60,
    user_id: 4,
    movie_id: 12,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 61,
    user_id: 4,
    movie_id: 44,
    caption: "",
    rating: 7,
    is_post: 1,
  },
  {
    id: 62,
    user_id: 4,
    movie_id: 21,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 63,
    user_id: 1,
    movie_id: 21,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 64,
    user_id: 1,
    movie_id: 44,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 65,
    user_id: 1,
    movie_id: 22,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 66,
    user_id: 1,
    movie_id: 14,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 67,
    user_id: 1,
    movie_id: 33,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 68,
    user_id: 1,
    movie_id: 36,
    caption: "Somehow even better than the original",
    rating: 9,
    is_post: 1,
  },
  {
    id: 69,
    user_id: 1,
    movie_id: 25,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 70,
    user_id: 1,
    movie_id: 45,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 71,
    user_id: 1,
    movie_id: 46,
    caption: "",
    rating: 5,
    is_post: 0,
  },
  {
    id: 72,
    user_id: 1,
    movie_id: 47,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 73,
    user_id: 1,
    movie_id: 48,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 74,
    user_id: 1,
    movie_id: 49,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 75,
    user_id: 5,
    movie_id: 50,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 76,
    user_id: 5,
    movie_id: 17,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 77,
    user_id: 5,
    movie_id: 51,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 78,
    user_id: 5,
    movie_id: 52,
    caption: "",
    rating: 8,
    is_post: 1,
  },
  {
    id: 79,
    user_id: 5,
    movie_id: 53,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 80,
    user_id: 5,
    movie_id: 54,
    caption: "",
    rating: 7,
    is_post: 1,
  },
  {
    id: 81,
    user_id: 5,
    movie_id: 55,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 82,
    user_id: 5,
    movie_id: 56,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 83,
    user_id: 5,
    movie_id: 16,
    caption: "",
    rating: 10,
    is_post: 0,
  },
  {
    id: 84,
    user_id: 5,
    movie_id: 57,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 85,
    user_id: 5,
    movie_id: 39,
    caption: "",
    rating: 3,
    is_post: 0,
  },
  {
    id: 86,
    user_id: 5,
    movie_id: 3,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 87,
    user_id: 5,
    movie_id: 4,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 88,
    user_id: 5,
    movie_id: 57,
    caption: "",
    rating: 10,
    is_post: 0,
  },
  {
    id: 89,
    user_id: 5,
    movie_id: 21,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 90,
    user_id: 6,
    movie_id: 2,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 91,
    user_id: 6,
    movie_id: 58,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 92,
    user_id: 6,
    movie_id: 59,
    caption: "Scary movie, but a little unrealistic",
    rating: 7,
    is_post: 1,
  },
  {
    id: 93,
    user_id: 6,
    movie_id: 60,
    caption:
      "Terrifying movie -- I'd highly recommend to any horror fans out there!",
    rating: 9,
    is_post: 1,
  },
  {
    id: 94,
    user_id: 6,
    movie_id: 61,
    caption: "Scariest movie I've seen all year",
    rating: 8,
    is_post: 1,
  },
  {
    id: 95,
    user_id: 6,
    movie_id: 62,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 96,
    user_id: 6,
    movie_id: 63,
    caption: "",
    rating: 10,
    is_post: 0,
  },
  {
    id: 97,
    user_id: 6,
    movie_id: 64,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 98,
    user_id: 6,
    movie_id: 65,
    caption: "Confusing and unintentionally funny ",
    rating: 5,
    is_post: 1,
  },
  {
    id: 99,
    user_id: 3,
    movie_id: 66,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 100,
    user_id: 3,
    movie_id: 67,
    caption:
      "Disappointing from Woody Allen -- very much carried by Jesse Eisenberg",
    rating: 6,
    is_post: 1,
  },
  {
    id: 101,
    user_id: 3,
    movie_id: 68,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 102,
    user_id: 3,
    movie_id: 69,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 103,
    user_id: 3,
    movie_id: 70,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 104,
    user_id: 3,
    movie_id: 71,
    caption: "If you haven't seen this classic before, you should now",
    rating: 10,
    is_post: 1,
  },
  {
    id: 105,
    user_id: 3,
    movie_id: 72,
    caption: "",
    rating: 10,
    is_post: 0,
  },
  {
    id: 106,
    user_id: 3,
    movie_id: 73,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 107,
    user_id: 3,
    movie_id: 74,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 108,
    user_id: 4,
    movie_id: 75,
    caption: "",
    rating: 10,
    is_post: 0,
  },
  {
    id: 109,
    user_id: 4,
    movie_id: 76,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 110,
    user_id: 4,
    movie_id: 77,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 111,
    user_id: 4,
    movie_id: 78,
    caption: "",
    rating: 4,
    is_post: 0,
  },
  {
    id: 112,
    user_id: 4,
    movie_id: 79,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 113,
    user_id: 4,
    movie_id: 80,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 114,
    user_id: 4,
    movie_id: 81,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 115,
    user_id: 4,
    movie_id: 82,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 116,
    user_id: 4,
    movie_id: 83,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 117,
    user_id: 4,
    movie_id: 20,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 118,
    user_id: 4,
    movie_id: 84,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 119,
    user_id: 4,
    movie_id: 85,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 120,
    user_id: 4,
    movie_id: 86,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 121,
    user_id: 4,
    movie_id: 87,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 122,
    user_id: 4,
    movie_id: 88,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 123,
    user_id: 1,
    movie_id: 89,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 124,
    user_id: 1,
    movie_id: 90,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 125,
    user_id: 1,
    movie_id: 91,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 126,
    user_id: 1,
    movie_id: 18,
    caption: "",
    rating: 10,
    is_post: 0,
  },
  {
    id: 127,
    user_id: 1,
    movie_id: 92,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 128,
    user_id: 1,
    movie_id: 93,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 129,
    user_id: 1,
    movie_id: 94,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 130,
    user_id: 1,
    movie_id: 95,
    caption: "Really did the book justice",
    rating: 9,
    is_post: 1,
  },
  {
    id: 131,
    user_id: 1,
    movie_id: 65,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 132,
    user_id: 1,
    movie_id: 77,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 133,
    user_id: 1,
    movie_id: 96,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 134,
    user_id: 1,
    movie_id: 97,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 135,
    user_id: 7,
    movie_id: 98,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 136,
    user_id: 7,
    movie_id: 99,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 137,
    user_id: 7,
    movie_id: 100,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 138,
    user_id: 7,
    movie_id: 101,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 139,
    user_id: 7,
    movie_id: 102,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 140,
    user_id: 7,
    movie_id: 103,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 141,
    user_id: 7,
    movie_id: 104,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 142,
    user_id: 7,
    movie_id: 105,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 143,
    user_id: 7,
    movie_id: 106,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 144,
    user_id: 7,
    movie_id: 107,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 145,
    user_id: 7,
    movie_id: 108,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 146,
    user_id: 7,
    movie_id: 109,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 147,
    user_id: 7,
    movie_id: 110,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 148,
    user_id: 7,
    movie_id: 111,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 149,
    user_id: 8,
    movie_id: 95,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 150,
    user_id: 8,
    movie_id: 61,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 151,
    user_id: 8,
    movie_id: 63,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 152,
    user_id: 8,
    movie_id: 104,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 153,
    user_id: 8,
    movie_id: 112,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 154,
    user_id: 8,
    movie_id: 113,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 155,
    user_id: 8,
    movie_id: 114,
    caption: "",
    rating: 9,
    is_post: 0,
  },
  {
    id: 156,
    user_id: 8,
    movie_id: 115,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 157,
    user_id: 8,
    movie_id: 9,
    caption: "",
    rating: 8,
    is_post: 0,
  },
  {
    id: 158,
    user_id: 8,
    movie_id: 19,
    caption: "",
    rating: 6,
    is_post: 0,
  },
  {
    id: 159,
    user_id: 8,
    movie_id: 10,
    caption: "",
    rating: 7,
    is_post: 0,
  },
  {
    id: 160,
    user_id: 8,
    movie_id: 15,
    caption: "",
    rating: 8,
    is_post: 0,
  },
];
