const bcrypt = require("bcryptjs");

module.exports = [
  {
    id: 1,
    name: "Ollie Law",
    username: "ollie_law",
    email: "ollielaw@moviegram.com",
    password: bcrypt.hashSync("password123"),
    bio: "Action Movie Enthusiast",
    avatar_url: "",
  },
  {
    id: 2,
    name: "John Smith",
    username: "johnnysmith4",
    email: "johnsmith@moviegram.com",
    password: bcrypt.hashSync("password123"),
    bio: "",
    avatar_url: "",
  },
  {
    id: 3,
    name: "Harry Robinson",
    username: "harryrobo01",
    email: "harryrobinson@moviegram.com",
    password: bcrypt.hashSync("password123"),
    bio: "",
    avatar_url: "",
  },
  {
    id: 4,
    name: "Sharon Ng",
    username: "sharon_ng",
    email: "sharonng@moviegram.com",
    password: bcrypt.hashSync("password123"),
    bio: "",
    avatar_url: "",
  },
  {
    id: 5,
    name: "Alana Thomas",
    username: "alanat3",
    email: "alanathomas@moviegram.com",
    password: bcrypt.hashSync("password123"),
    bio: "",
    avatar_url: "",
  },
  {
    id: 6,
    name: "Vanessa Mendoza",
    username: "vmendoza",
    email: "vanessamendoza@moviegram.com",
    password: bcrypt.hashSync("password123"),
    bio: "",
    avatar_url: "",
  },
];
